In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('RecyclingCentres_Bavaria.csv')

C:\Users\SAM\AppData\Local\Temp\ipykernel_18260\3934355223.py:1: DtypeWarning: Columns (3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,43,44,45,46,47,48,49,50,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('RecyclingCentres_Bavaria.csv')

In [4]:
df.head()

,id,lat,lon,cans,clothes,shoes,waste,capacity,used_fat,beverage_cartons,...,special_waste,glass_related_recycling,electrical_related_recycling,metal_related_recycling,packaging_wastes,paper_wastes,plastic_wastes,organic_wastes,construction_wastes,hazardous/toxic
0,25916382,49.707694,10.861700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,26371241,49.684979,10.879875,yes,yes,NaN,NaN,NaN,NaN,NaN,...,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,26584875,48.462549,11.828062,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,26629845,49.603979,11.136337,yes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,yes,NaN,NaN,NaN,yes,yes,NaN,NaN,NaN
4,26685048,49.948760,11.556301,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.isna().sum()

id                                  0
lat                                 0
lon                                 0
cans                            17270
clothes                         16054
shoes                           19216
waste                           20976
capacity                        21124
used_fat                        21129
beverage_cartons                20815
cooking_oil                     21104
clothes:operator                21117
collection_times                21117
drugs                           21128
bulky_waste                     21129
residual_waste                  21130
aerosol_cans                    21129
textiles                        21130
clothes.1                       21129
waste.1                         21120
gas_bottles                     21126
operator:clothes                21130
fee                             21129
paint                           21129
car_batteries                   21129
bin                             21130
aluminium_cans                  21130
industrial                      21130
duvet                           21130
ground_transport                21130
tin_cans                        21128
aerosols                        21130
automotive_batteries            21131
lamps                           21131
landfill:class                  21131
landfill:waste                  21131
bicycles                        21131
composites                      21131
others                          21131
bags                            21131
candle_wax                      21131
energy_waste                    21131
special_waste                   21131
glass_related_recycling         13403
electrical_related_recycling    20418
metal_related_recycling         20199
packaging_wastes                20313
paper_wastes                    18729
plastic_wastes                  19870
organic_wastes                  20333
construction_wastes             21120
hazardous/toxic                 21113
dtype: int64

In [7]:
df.columns

Index(['id', 'lat', 'lon', 'cans', 'clothes', 'shoes', 'waste', 'capacity',
       'used_fat', 'beverage_cartons', 'cooking_oil', 'clothes:operator',
       'collection_times', 'drugs', 'bulky_waste', 'residual_waste',
       'aerosol_cans', 'textiles', 'clothes.1', 'waste.1', 'gas_bottles',
       'operator:clothes', 'fee', 'paint', 'car_batteries', 'bin',
       'aluminium_cans', 'industrial', 'duvet', 'ground_transport', 'tin_cans',
       'aerosols', 'automotive_batteries', 'lamps', 'landfill:class',
       'landfill:waste', 'bicycles', 'composites', 'others', 'bags',
       'candle_wax', 'energy_waste', 'special_waste',
       'glass_related_recycling', 'electrical_related_recycling',
       'metal_related_recycling', 'packaging_wastes', 'paper_wastes',
       'plastic_wastes', 'organic_wastes', 'construction_wastes',
       'hazardous/toxic'],
      dtype='object')

In [11]:
import pandas as pd

# Create a copy of your dataset to work with
merged_df = df.copy()

# Define the list of columns that need to be reversed
one_hot_columns = ['cans', 'clothes', 'shoes', 'waste', 'capacity',
                   'used_fat', 'beverage_cartons', 'cooking_oil', 'clothes:operator',
                   'collection_times', 'drugs', 'bulky_waste', 'residual_waste',
                   'aerosol_cans', 'textiles', 'clothes.1', 'waste.1', 'gas_bottles',
                   'operator:clothes', 'fee', 'paint', 'car_batteries', 'bin',
                   'aluminium_cans', 'industrial', 'duvet', 'ground_transport', 'tin_cans',
                   'aerosols', 'automotive_batteries', 'lamps', 'landfill:class',
                   'landfill:waste', 'bicycles', 'composites', 'others', 'bags',
                   'candle_wax', 'energy_waste', 'special_waste',
                   'glass_related_recycling', 'electrical_related_recycling',
                   'metal_related_recycling', 'packaging_wastes', 'paper_wastes',
                   'plastic_wastes', 'organic_wastes', 'construction_wastes',
                   'hazardous/toxic']

# Loop through each one-hot encoded column
for column in one_hot_columns:
    # Create a new column with the original column name and assign 1 where 'yes' is present, 0 otherwise
    merged_df[column] = (merged_df[column] == 'yes').astype(int)

In [13]:
pd.set_option('display.max_columns',None)

In [14]:
merged_df.head()
# This could also work

,id,lat,lon,cans,clothes,shoes,waste,capacity,used_fat,beverage_cartons,cooking_oil,clothes:operator,collection_times,drugs,bulky_waste,residual_waste,aerosol_cans,textiles,clothes.1,waste.1,gas_bottles,operator:clothes,fee,paint,car_batteries,bin,aluminium_cans,industrial,duvet,ground_transport,tin_cans,aerosols,automotive_batteries,lamps,landfill:class,landfill:waste,bicycles,composites,others,bags,candle_wax,energy_waste,special_waste,glass_related_recycling,electrical_related_recycling,metal_related_recycling,packaging_wastes,paper_wastes,plastic_wastes,organic_wastes,construction_wastes,hazardous/toxic
0,25916382,49.707694,10.861700,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,26371241,49.684979,10.879875,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
2,26584875,48.462549,11.828062,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,26629845,49.603979,11.136337,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,1,0,0,0
4,26685048,49.948760,11.556301,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [15]:
merged_df_1 = df.copy()

# Define the list of columns that need to be reversed (those containing 'yes')
one_hot_columns = ['cans', 'clothes', 'shoes', 'waste', 'capacity',
                   'used_fat', 'beverage_cartons', 'cooking_oil', 'clothes:operator',
                   'collection_times', 'drugs', 'bulky_waste', 'residual_waste',
                   'aerosol_cans', 'textiles', 'clothes.1', 'waste.1', 'gas_bottles',
                   'operator:clothes', 'fee', 'paint', 'car_batteries', 'bin',
                   'aluminium_cans', 'industrial', 'duvet', 'ground_transport', 'tin_cans',
                   'aerosols', 'automotive_batteries', 'lamps', 'landfill:class',
                   'landfill:waste', 'bicycles', 'composites', 'others', 'bags',
                   'candle_wax', 'energy_waste', 'special_waste',
                   'glass_related_recycling', 'electrical_related_recycling',
                   'metal_related_recycling', 'packaging_wastes', 'paper_wastes',
                   'plastic_wastes', 'organic_wastes', 'construction_wastes',
                   'hazardous/toxic']

# Loop through each one-hot encoded column and replace 'yes' with column name
for column in one_hot_columns:
    merged_df_1[column] = merged_df_1[column].apply(lambda x: column if x == 'yes' else '')

# Concatenate the original categorical columns into a single column
merged_df_1['reversed_category'] = merged_df_1[one_hot_columns].apply(lambda x: ' '.join(x), axis=1)

In [16]:
merged_df_1.head()

,id,lat,lon,cans,clothes,shoes,waste,capacity,used_fat,beverage_cartons,cooking_oil,clothes:operator,collection_times,drugs,bulky_waste,residual_waste,aerosol_cans,textiles,clothes.1,waste.1,gas_bottles,operator:clothes,fee,paint,car_batteries,bin,aluminium_cans,industrial,duvet,ground_transport,tin_cans,aerosols,automotive_batteries,lamps,landfill:class,landfill:waste,bicycles,composites,others,bags,candle_wax,energy_waste,special_waste,glass_related_recycling,electrical_related_recycling,metal_related_recycling,packaging_wastes,paper_wastes,plastic_wastes,organic_wastes,construction_wastes,hazardous/toxic,reversed_category
0,25916382,49.707694,10.861700,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,26371241,49.684979,10.879875,cans,clothes,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,glass_related_recycling,,,,,,,,,cans clothes ...
2,26584875,48.462549,11.828062,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
3,26629845,49.603979,11.136337,cans,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,glass_related_recycling,,,,paper_wastes,plastic_wastes,,,,cans gl...
4,26685048,49.948760,11.556301,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

In [17]:
merged_df_1.drop(columns=one_hot_columns, inplace=True)

In [20]:
merged_df_1.head(20)

,id,lat,lon,reversed_category
0,25916382,49.707694,10.861700,
1,26371241,49.684979,10.879875,cans clothes ...
2,26584875,48.462549,11.828062,
3,26629845,49.603979,11.136337,cans gl...
4,26685048,49.948760,11.556301,
5,26685050,49.948860,11.574815,glass_...
6,26939823,49.948737,11.552307,cans gl...
7,27157744,48.453795,11.652519,
8,27313199,50.014129,9.064173,
9,27313274,49.996713,9.070234,cans gl...
10,27313275,49.999346,9.076994,
11,27446673,50.005597,9.055332,
12,27561550,48.447885,11.766794,
13,27773045,49.943280,11.564585,glass_...
14,29756460,49.957882,10.941464,glass_...
15,29776318,48.098009,11.790576,cans clothes shoes ...
16,30211570,49.930899,10.865161,cans clothes ...
17,30310857,49.942090,11.545586,
18,30705557,50.003328,9.063541,cans clothes ...
19,30850130,49.987980,9.113603,cans gl...

In [22]:
merged_df = df.copy()

# Define the list of columns that need to be reversed (those containing 'yes')
one_hot_columns = ['cans', 'clothes', 'shoes', 'waste', 'capacity',
                   'used_fat', 'beverage_cartons', 'cooking_oil', 'clothes:operator',
                   'collection_times', 'drugs', 'bulky_waste', 'residual_waste',
                   'aerosol_cans', 'textiles', 'clothes.1', 'waste.1', 'gas_bottles',
                   'operator:clothes', 'fee', 'paint', 'car_batteries', 'bin',
                   'aluminium_cans', 'industrial', 'duvet', 'ground_transport', 'tin_cans',
                   'aerosols', 'automotive_batteries', 'lamps', 'landfill:class',
                   'landfill:waste', 'bicycles', 'composites', 'others', 'bags',
                   'candle_wax', 'energy_waste', 'special_waste',
                   'glass_related_recycling', 'electrical_related_recycling',
                   'metal_related_recycling', 'packaging_wastes', 'paper_wastes',
                   'plastic_wastes', 'organic_wastes', 'construction_wastes',
                   'hazardous/toxic']

# Loop through each one-hot encoded column and replace 'yes' with column name
for column in one_hot_columns:
    merged_df[column] = merged_df[column].apply(lambda x: column if x == 'yes' else '')

# Concatenate the original categorical columns into a single column
merged_df['reversed_category'] = merged_df[one_hot_columns].apply(lambda x: ' '.join([value for value in x if value]), axis=1)

# Drop the original one-hot encoded columns
merged_df.drop(columns=one_hot_columns, inplace=True)

In [23]:
merged_df.head()

,id,lat,lon,reversed_category
0,25916382,49.707694,10.861700,
1,26371241,49.684979,10.879875,cans clothes glass_related_recycling
2,26584875,48.462549,11.828062,
3,26629845,49.603979,11.136337,cans glass_related_recycling paper_wastes plas...
4,26685048,49.948760,11.556301,

In [25]:
merged_df.to_csv('Recyclingcentres_Bavaria_collapsed.csv', index=False)

### Conclusion
The way I see it is that the columns seem to appear in a way of one hot encoded so I suggest that we use the columns as it as replace the yes with the 1

Other way we could approach this is by decoding the encoding and in that way compiling all the columns into into one as evident in the Recyclingcentres_Bavaria_collapsed.csv But I think this might be less useful